[startup]
listenPort = 7698
databaseNumber = 16
threadNum = 0
serverLogPath = "/mnt/e/jr/FoxbatDB/out/log/foxbatdb.log"
serverLogMaxFileSizeMB = 512
serverLogMaxFileNumber = 10
serverLogFlushPeriodSec = 5

[aof]
aofCronJobPeriodMs = 3000
aofLogFilePath = "/mnt/e/jr/FoxbatDB/out/log/foxbatdb.oplog"

[dbfile]
dbFileDirectory = "/mnt/e/jr/FoxbatDB/out/log/db"
dbFileMaxSizeMB = 512
dbFileMergeThreshold = 1
dbFileMergeCronJobPeriodMs = 3000

[keyval]
keyMaxBytes = 10240
valueMaxBytes = 10240

[memory]
# maxmemoryPolicy = "noeviction"
maxmemoryPolicy = "allkeys-lru"
memoryPoolMinSize = 4096