[startup]
listenPort = 7698
databaseNumber = 16
serverLogPath = "log/foxbatdb.log"
serverLogMaxFileSizeMB = 512
serverLogMaxFileNumber = 10
serverLogFlushPeriodSec = 5

[aof]
aofCronJobPeriodMs = 3000
aofLogFilePath = "foxbatdb.oplog"

[dbfile]
dbFileDirectory = "db"
dbFileMaxSizeMB = 512

[keyval]
keyMaxBytes = 1024
valueMaxBytes = 1024